### ISSUE TITLE
Episode Details: Playback error box is skipped by talkback

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#686] opened 2023-01-11 06:33 UTC
### Description

Playback error box is skipped by talkback on the episode details screen.

Noticed in https://github.com/Automattic/pocket-casts-android/pull/683#pullrequestreview-1242387499.

### Step-by-step reproduction instructions

1. Go to the episode details screen 
2. Enable airplane mode
3. Tap on the play icon
4. Notice that an error box is displayed
5. Enable talkback
6. Notice that playback error box is skipped by talkback

### Screenshots or screen recording

https://user-images.githubusercontent.com/1405144/211734354-6a741733-d2c8-4929-91bf-45c7fe637783.mp4

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by mebarbosa** [comment] 2024-02-16 17:01
Hey @ashiagr we can't reproduce this issue anymore since we are queueing the podcast download when we don't have internet connection. I think we could close this issue. What do you think?

**Closed** 2024-03-15 10:54 UTC
Labels: bug, Accessibility
