### ISSUE TITLE
Hashtag Truncates Chapter Title

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#144] opened 2022-07-20 21:04 UTC
Chapter titles that contain a hashtag get truncated.

### Steps to Reproduce

1. On the Android app, view an episode that has a chapter title with a hashtag. Here's an example: [Switching to iPhone 13… Right?](https://pca.st/episode/11ff5096-c2f5-49ad-882a-e69bd7f26997).
2. The title gets truncated at the hashtag.

#### Episode with chapter title "Founding Member of the #ScratchFlipGang"
<img width="350px" src="https://user-images.githubusercontent.com/74066241/147025849-5880edd6-1082-47d2-b01b-8f185e23229a.jpg"/>

### Additional Information

- Reported in #4528361-zen

- The original report was for a Pixel 5, and the issue is no longer occurring for them on version 7.19.1. Issue still occurs on Samsung SM-N9860 even on version 7.19.1 though.

#### Another device this happens on:
Phone: samsung - c2q - SM-N9860 - c2q
Kernel: 4.19.113-22701397 - 21DJFA19
Android version: 11 SDK 30

**Comment by josepatinob** [comment] 2023-02-16 21:17
Couldn't reproduce using the below device and app version.
Phone: Pixel 6a
App Version: 7.31 (9073)
Android Version: 13

**Comment by mebarbosa** [comment] 2024-05-29 15:18
I can confirm this is already fixed in `7.64`

![Screenshot_20240529_121706_Pocket Casts](https://github.com/Automattic/pocket-casts-android/assets/42220351/5c9d6fc6-8a4a-4aa4-bb85-5e0f91957595)

**Closed by mebarbosa** 2024-05-29 15:18 UTC
Labels: bug, migrated
