### ISSUE TITLE
Tasker Integration broken in 7.66-rc-1

### ISSUE THREAD

**Issue by b-aaron** [Automattic/pocket-casts-android#2354] opened 2024-06-15 15:44 UTC
### Description

Using the Tasker integration is broken in the latest Beta Update.
All of Querying and Playing Episodes / Filters or Adding to Up Next does not work. There is no error being received either.
Pocket Casts has also crashed some times, while testing.

### Step-by-step reproduction instructions

(I am only using MacroDroid with the Tasker Plugin, so I can only give instructions for that.)
1. Create Macro
2. Add Action -> Applications -> Tasker/Locale Plugin -> Pocket Casts
3. Select Event Type (Querying / Playing / Adding to Up Next) for testing I used Playing Filter.
4. Select Filter
5. (Optionally add variable for error message)
6. Click on created Action
7. Test Action
8. Notice Pocket Casts does not start playing (and might crash)
9. (Notice error message variable stays empty)

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/72910336/403f4c0e-b605-449e-b97b-4726cd569206

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Galaxy S23 FE
Android 14 OneUI 6.1
Pocket Casts 7.66-rc-1

**Comment by b-aaron** [comment] 2024-06-15 16:15
Looked into it a bit more, and the app crashes every time. Here's one of the Crash Logs.

```
E 15/6 18:12:24 Fatal crash.
android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c0eb8b9 10760:au.com.shiftyjelly.pocketcasts/u0a494} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
	at android.app.Service.startForeground(Service.java:775)
	at cd.n$a.b(SourceFile:29)
	at cd.n$a.c(SourceFile:21)
	at cd.f.k(SourceFile:5)
	at com.joaomgcd.taskerpluginlibrary.action.IntentServiceAction.g(SourceFile:6)
	at cd.f.h(SourceFile:6)
	at cd.f.b(SourceFile:1)
	at cd.b.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by MiSikora** [comment] 2024-06-18 05:40
> Looked into it a bit more, and the app crashes every time. Here's one of the Crash Logs.

This crash is [a system restriction](https://developer.android.com/develop/background-work/services/foreground-services#bg-access-restrictions) imposed by Android since Android 12, and there's nothing we can really do about it. If app is closed other apps cannot start foreground services. And because playback in Pocket Casts is controlled by a foreground service it throws this exceptions.

**Comment by MiSikora** [comment] 2024-06-18 07:06
I initially thought that the issue is with the OS restrictions regarding starting foreground services. But the issue is with the Tasker plugin library itself. Sorry if anyone got confused by my previous comment.

I'll close this now but feel free to re-open if the issue persists in `7.66-rc-2` once its out.

**Closed by MiSikora** 2024-06-18 07:06 UTC
Labels: bug
