### ISSUE TITLE
Add a bookmark button to the media actions 

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2851] opened 2024-09-13 04:40 UTC
### Description

It would be useful to have the bookmark button easily accessible from the media actions and Android Auto. It could be added to the list of actions that can be used, and the user could rearrange them so it appears.

### Screenshots or screen recording

<img  width="300" src="https://github.com/user-attachments/assets/5fe79be9-eb8d-468e-afe3-0e534d242824" /> 

### Did you search for existing list?

- [X] I have searched for existing issues.

**Comment by CookieyedCodes** [comment] 2024-09-13 05:21
Great for the new android media player too :)

**Comment by MiSikora** [comment] 2024-10-01 12:22
Duplicate of #1669

**Closed by MiSikora** 2024-10-01 12:22 UTC
Labels: [Priority] Low, [Type] Enhancement, [Area] Notification
