### ISSUE TITLE
Pressing the thumbnail of the widget opens the app on that episode's page, instead of the main app page.

### ISSUE THREAD

**Issue by BramKaandorp** [Automattic/pocket-casts-android#2091] opened 2024-04-19 17:13 UTC
### Description

The Widget isn't working properly. When I press the thumbnail image, it opens the current episode's description page, instead of opening the app like it would through the icon in the launcher.

### Step-by-step reproduction instructions

Go to the home screen with the widget.
Press the thumbnail in the widget.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Fairphone 4 (Android 13)
Lenovo Tab P11 2n gen (Android 13)

**Comment by CookieyedCodes** [comment] 2024-04-19 22:18
To be honest I don't mind that, now potentially if you hit the pocketcasts logo or the background I wouldn't mind it going to the podcasts screen tho :)

**Comment by MiSikora** [comment] 2024-04-22 05:48
This is expected and not a bug. I'll close this issue and forward your feedback about widgets' behavior.

**Closed by MiSikora** 2024-04-22 05:48 UTC
Labels: bug

**Comment by BramKaandorp** [comment] 2024-04-22 07:28
That surprises me, as there is no other media playing app that does this. The most any other app does is open the player window, not the page that gives information on the thing you're playing.

Imagine if YouTube Music always opened the album page when you tapped the thumbnail in the widget, instead of the main app page. It's information that's not needed at that moment.

**Comment by CookieyedCodes** [comment] 2024-04-22 08:03
@BramKaandorp to me it makes sence because it gives to the quick options for play/pause/play now, archive, mark as played, starred, share, download/delete, add to upnext & shownotes all from the one menu and theirs a setting for if you hit play on any podcast it will load now playing (archive also dismisses the dialogue), so it's not that now playing is that far away in my opinion 😅, now playing probably should be sent for the currently playing episode tho & a stared icon should probably be added to - the medium & big widgits in my opinion 😅
