### ISSUE TITLE
Add Support for Embedded Artwork in Mini and Notification Players

### ISSUE THREAD

**Issue by igotdes** [Automattic/pocket-casts-android#680] opened 2023-01-09 07:49 UTC
### What problem does this address?

Currently, embedded artwork on the Android app only shows up in the full-sized player.

This was first reported in #5835766-zen.

### What is your proposed solution?

Look into implementing embedded artwork for both the mini and notification players in Android.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by mchowning** [comment] 2023-12-19 03:43
Related to https://github.com/Automattic/pocket-casts-android/issues/1608

**Comment by ashiagr** [comment] 2023-12-27 10:43
Closing this feature request as it is a duplicate of https://github.com/Automattic/pocket-casts-android/issues/1608

**Closed by ashiagr** 2023-12-27 10:43 UTC
Labels: feature request
