### ISSUE TITLE
Sleep Timer: Won't stop at end of episode

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#141] opened 2022-07-20 20:50 UTC
We've had 2 users report that setting the sleep timer to the end of the episode failed to work and instead playback continued with the next episode in the up next queue after a bit of time.

> The sleep timer is not working. Specifically, when I try to set a sleep timer to stop at the end of the episode, it continues to play the next podcast in my queue.
>
> For the past month or so, when I've used the sleep timer, the most recently played podcast will restart an hour or two after the sleep timer stops it. Since I use this feature to fall asleep, having the podcast suddenly restart wakes me up and kinda defeats the purpose of using it to help me fall asleep.

**Comment by mebarbosa** [comment] 2024-05-10 12:44
Closed this issue since I can't reproduce it anymore. We will keep track on it in case someone reports this again

**Closed** 2024-05-10 12:43 UTC
Labels: bug, migrated
