### ISSUE TITLE
Screen glitch/flicker when adjusting volume while chromecasting

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#506] opened 2022-10-28 13:28 UTC
### Description

A user is seeing the screen glitch/flicker when adjusting the volume casting to a Google Home device. 

5641095-zd-woothemes

Originally raised by @joashrajin in https://github.com/Automattic/pocket-casts-android/issues/140#issuecomment-1294916896.

### Step-by-step reproduction instructions

Not sure, because I have not been able to reproduce this on two devices:
1. Pixel 6 Pro, Android 13, PC 7.24.2
2. Samsunt A13, Android 12, PC 7.25.0

### Screenshots or screen recording

https://user-images.githubusercontent.com/16253818/198582907-bfd9cdd8-8097-4434-a8df-cb2a527ff66e.mp4

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App version : 7.23 (9031)
Phone: Google - Panther - Pixel 7 - panther
Kernel: 5.10.107-android13-4-00004-g6522bf85d262-ab8935228 - abfarm-release-rbe-64-00018
Android version: 13 SDK 33

**Comment by geekygecko** [comment] 2024-08-29 22:47
I'm closing this as I can't reproduce it and it has had no more reports.

**Closed by geekygecko** 2024-08-29 22:47 UTC
Labels: [Type] Bug
