### ISSUE TITLE
Full screen player shows old show notes after switching episodes

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#27] opened 2022-07-01 10:35 UTC
Reported [in Slack](https://a8c.slack.com/archives/C02A333D8LQ/p1651230852115379)

Steps to repeat.
1. Play an episode
2. Add another episode to the Up Next
3. Open the full screen player
4. Switch to the Notes tab
5. Switch back to the Now Playing tab
6. Archive the episode from the shelf
7. Quickly switch back to the Notes tab
The old show notes will still be there for a short period of time while the new show notes are downloaded.

- [ ] Clear the show notes when we switch episodes.
- [ ] Check if the show notes are getting loaded straight away.
- [ ] Show a loading indicator in the app while the show notes are being downloaded.

https://user-images.githubusercontent.com/308331/166168270-7a5d9433-f6f0-42de-8088-80335ca38b2a.mp4

**Comment by mdrockwell** [comment] 2022-12-13 19:24
Reopening this. Another user is experiencing it here: 5781236-zd-woothemes

App version : 7.27.1 (9055)
Phone: samsung - TECNO P3S - SM-G998B - p3s
Kernel: 5.4.147-25305783-abG998BXXS5DVK1 - 21DK7B11
Android version: 13 SDK 33

**Comment by ashiagr** [comment] 2022-12-29 09:47
Another report: 5821523-zd-woothemes

> Sometimes the podcast notes render the notes for the previous podcast I looked at and not the current one.

**Comment by rezzap** [comment] 2023-05-25 20:14
another report in 6305956-zd-woothemes

> When I switch between podcast episodes, the description will still be displayed for the previous episode that I was listening to, not the episode that I'm now listening to. Here's an example where you can see that the title which is correct is completely unrelated to the episode description which came from another podcast and obviously another episode.

App Version: 7.38
Phone: Pixel 7
Android 13

The user reports that this has been happening regularly for more than a year, so also on Pixel 3A,  Android 12, and multiple earlier versions of PC.

![Screenshot_20230518-220307](https://github.com/Automattic/pocket-casts-android/assets/10325627/542eeb6e-dbea-4ecc-8ce2-f2360b3f9c1f)

**Comment by NiggleHub** [comment] 2023-07-05 13:02
Had this (or very similar) issue last week, running 7.42-rc-3 (9112).

The notes displayed in the ‘Notes’ tab (in the player, to the right of the ‘Playing’ tab) for a particular podcast were wrong. Pocket Cast showed the notes from an unrelated earlier-played podcast. Strange thing was that the notes displayed outside the player, i.e. below the podcast summary and play button, were correct.

Resolved itself the following day, for the same podcast. Three screenshots attached, for Day 1 (wrong and correct cases) and Day 2 (correct case).

Nigel

![Day 1 - Wrong](https://github.com/Automattic/pocket-casts-android/assets/85678567/97319a87-67f0-4610-973e-018ccc9014c3)
![Day 1 - Correct](https://github.com/Automattic/pocket-casts-android/assets/85678567/7eb2d932-bd26-414a-8d0f-d12ee228b631)
![Day 2 - Correct](https://github.com/Automattic/pocket-casts-android/assets/85678567/8949c09b-b404-4951-9898-54f642dfb539)

**Comment by joashrajin** [comment] 2023-07-06 09:55
+1 in 6499663-zd-woothemes

Phone: samsung - r0s - SM-S901B - r0s
Kernel: 5.10.136-android12-9-26203352-abS901BXXU5CWEA - 21DK7913
Android version: 13 SDK 33

**Comment by mdrockwell** [comment] 2023-07-13 15:24
Looks to be another case of this here: 6529398-zd-woothemes

Phone: Google - cheetah - Pixel 7 Pro - cheetah
Kernel: 5.10.157-android13-4-00001-g914e947b041d-ab10144456 - abfarm-release-rbe-64-2004-0056
App version : 7.42 (9113)

**Comment by erricgunawan** [comment] 2023-07-14 08:28
6533738-zen

> Phone: OnePlus - OnePlus 9 5G - LE2117 - OnePlus9TMO
Kernel: 5.4.210-qgki-g0249e0bcff37 - dg02-pool03-kvm82
Android version: 13 SDK 33
App version : 7.43-rc-1 (9114)

**Comment by erricgunawan** [comment] 2023-08-25 05:59
> The Notes tab for the currently playing podcast is showing notes for an entirely different podcast rather than the one currently playing. Compare the attached screenshots to see what I mean.

> Phone: Google - Pixel 5 - Pixel 5 - redfin
Kernel: 4.19.269-g8728c337137c-ab10161573 - abfarm-release-rbe-64-2004-0099
Android version: 13 SDK 33
App version : 7.45 (9128)

6720624-zen

**Comment by joashrajin** [comment] 2023-09-07 14:40
> it seems like after an update for about the last couple weeks at least, Pocket casts no longer shows the notes for a podcast eposode when I'm offline. I have to have cell reception for the notes to refresh for each episode. Also when I'm offline it seems like the icons for each podcast are missing and I also have to be online to get those. 

Recording: 

https://github.com/Automattic/pocket-casts-android/assets/16253818/7cf31fbe-43f9-44bf-b140-ddd3d7ede18a


Slack thread: p1691639167918569-slack-C02A333D8LQ

6621479-zd-a8c

**Comment by igotdes** [comment] 2023-09-11 03:46
#6796868-zen:

> When I am playing an episode, and go to the "Notes" page, whether by swiping left or by clicking the "Notes" tab, it always shows the correct *title* of the playing episode at top, but underneath the title, it sometimes shows the wrong episode description. 
> 
> Specifically, it displays the description of the episode that I played most recently, rather than for the episode that is actually playing. And it never corrects this unless I play a different episode and then return to this one, or else halt and restart PocketCasts.

**Comment by igotdes** [comment] 2023-10-03 11:53
#7114309-zen:

> I am consistently getting an error with the details of a currently playing podcast.  These are downloaded files, and when I look at the details for the currently playing podcast, it is displaying the details for the previous podcast I was listening to.
> 
> If this were a one off issue, I wouldn't trouble anyone, but I have consistently been having issues with the details not displaying correctly.

**Comment by igotdes** [comment] 2023-10-04 08:23
#7119442-zen:

> Just a note (after my subscription renewed) that this error is still happening.

**Comment by geekygecko** [comment] 2023-10-04 08:38
I have [raised a pull request](https://github.com/Automattic/pocket-casts-android/pull/1436) to hopefully help with some of these issues in version 7.50.

**Comment by mebarbosa** [comment] 2024-05-15 17:51
Closing this issue since I can't reproduce this anymore in `7.64-rc-1`. We can re-open this one in case someone complains about this again. It's seem these changes @geekygecko mentioned above were able to fix this

**Comment by igotdes** [comment] 2024-07-23 04:59
User who is on v7.68-rc-1 is reporting this issue again:

> I've been traveling this summer and am frequently without internet. All my podcasts episodes are downloaded on the phone to avoid any issues. Unfortunately the shownotes are always unavailable when offline.
> 
> Is this behavior expected ?
> Shouldn't shownotes, especially for downloaded episodes, be viewable when offline ?

I hope it's okay to reopen this issue. If a new issue is preferred, however, please let me know!

**Comment by MiSikora** [comment] 2024-09-11 05:52
The issue with the offline notes should be fixed here: https://github.com/Automattic/pocket-casts-android/pull/2681

I wasn't able to reproduce the original issue as well.

**Closed by MiSikora** 2024-09-11 05:52 UTC
Labels: [Type] Bug, [Priority] Low, [Area] Player UI
