### ISSUE TITLE
Multiselect: Does not work in some cases

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-android#1507] opened 2023-11-01 12:18 UTC
### Description

If I select an episode of a podcast from the "Up Next" list, the multi-select function doesn't work. However, if I back out to the main podcast list and select an episode from there, the multi-select function works perfectly.

### Step-by-step reproduction instructions

1. Tap on the Up Next List
2. Tap on any episode in the list
3. Tap on the podcast page link from the episode info
4. Long press on an episode in the Podcast Page when it loads to select it
5. Long press on the episode again to bring up the Select all menu

At this point, selecting any of the three options listed has no effect. Additionally, selecting "Select All" does not select anything.

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/16253818/bc838aae-48ed-4c45-80d5-c5963199d079

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold 4, Android 13, Pocket Casts v7.50

**Comment by thabotswana** [comment] 2023-11-22 13:41
Another report in 7307760-zd-a8c.

This seems to be related to an issue I reported in https://github.com/Automattic/pocket-casts-android/issues/187. 

I have now discovered that this only happens when the Up Next queue is empty. Here's a screen recording illustrating this.

https://github.com/Automattic/pocket-casts-android/assets/35628116/23a86ccd-2d62-41d2-b6f9-d675e1526344

**Comment by mchowning** [comment] 2023-12-21 02:12
Closing because I can no longer reproduce this. It was likely fixed by https://github.com/Automattic/pocket-casts-android/pull/1579.

**Closed by mchowning** 2023-12-21 02:12 UTC
Labels: bug
