### ISSUE TITLE
Page flashes if you tap the same bottom navigation option again

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#66] opened 2022-07-06 18:10 UTC
We should detect when we are already on that screen and either do nothing or, if we want to "reset" the view when we tap the icon again (i.e., return to the top of the page) do something like smoothly scrolling back to the top instead of having the screen flash white.

https://user-images.githubusercontent.com/4656348/177615475-8d040d84-3c9e-447d-8a20-ee4af0cac60c.mp4

**Comment by MiSikora** [comment] 2024-09-11 06:35
Duplicate of #2149

**Closed by MiSikora** 2024-09-11 06:35 UTC
Labels: Migrated, [Type] Enhancement, [Area] Navigation
