### ISSUE TITLE
Incorrect cast icon color on Podcasts page with Classic Theme

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#150] opened 2022-07-21 13:05 UTC
This issue has been migrated from the old repository.

**Message 1**
Using the Classic theme, the cast icon on the Podcasts page is not properly getting the white color applied to it.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/4656348/166390082-e34c399f-f3e5-4cc2-a63d-9dfe1afc179a.png">

It appears that this occurs because we recently added [a guard to prevent tinting that button with a color of `-1`](https://github.com/shiftyjelly/pocketcasts-android/blob/develop/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/chromecast/CastManagerImpl.kt#L47), which prevents true white (`#FFFFFF`) from being applied since that resolves to `-1`, but permits not-quite-white (`#FFFFFE`) to be applied since that resolves to `-2`. Removing the `-1`  check appears to fix this problem, but it's not clear to me why we added that check in the first place, so I wanted to see what your thoughts were here @geekygecko .

**Message 2**
It looks like the interface has a default of -1. 
```
fun setupMediaRouterMenuButton(menu: Menu, buttonId: Int, tintColor: Int = -1)
```
I don't think in Kotlin you can define default values in an override method.
Maybe we can just make that nullable, with a default of null.

**Message 3**
> Maybe we can just make that nullable, with a default of null.

I like that idea. I did do a quick test of it and it worked well, so I opened #3376.

I am wondering if there is another issue lurking here with our themes though. It feels like the default color for the icon should be white, not black. This also crops up if you tap the podcast tab when you already have the podcast tab open—you'll briefly see the overflow dots (and the cast icon if your `null` fix is applied) flip to black and before getting tinted to white. I haven't had a chance to look into that though.

In fact, on some themes the two icons switch to different colors:

<details><summary>Classic (both cast and overflow icons go black)</summary>

https://user-images.githubusercontent.com/4656348/166708864-5f9fd143-3a71-472f-af5d-30e80b8ae414.mp4

</details>

<details><summary>Electricity (cast goes white, overflow goes black)</summary>

https://user-images.githubusercontent.com/4656348/166708142-4631db61-f6df-4ea9-9b72-50d32bdf0741.mp4 

</details>

**Message 4**
I think I might have found a way to fix this for the overflow icon.

Before is on the left and after the change is on the right.
<img width="1084" alt="Screen Shot 2022-05-05 at 1 56 43 pm" src="https://user-images.githubusercontent.com/308331/166863638-06fa79cd-4fcb-4a66-bcc0-8b72d88b6110.png">

If we know the icons are just being used in the toolbar we can apply the theme color attribute in the vector drawable like the following:

<img width="865" alt="Screen Shot 2022-05-05 at 1 58 25 pm" src="https://user-images.githubusercontent.com/308331/166863735-f9d97d2a-c342-46c1-a0ce-d2fc5e66e27a.png">

**Comment by mchowning** [comment] 2023-11-30 02:44
I'm not able to reproduce these issues anymore, so I'll go ahead and close this.

<details><summary>Chromecast icon has correct tint with classic theme</summary>

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/ac29cac3-ce4a-434a-84c7-d462ae8707d9)

</details>

<details><summary>Toolbar icons don't temporarily have wrong color when loading with Classic theme</summary>



https://github.com/Automattic/pocket-casts-android/assets/4656348/4628c36c-72a4-4670-8812-be577703f732


</details> 


<details><summary>Toolbar icons don't temporarily have wrong color when loading with Electricity theme</summary>


https://github.com/Automattic/pocket-casts-android/assets/4656348/170898ab-5a13-4a84-95eb-fca28f14e0ec


</details>

**Closed by mchowning** 2023-11-30 02:44 UTC
